apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
    - name: spark
      port: 7077
      targetPort: 7077
  selector:
    component: spark-master-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master-service
  template:
    metadata:
      labels:
        component: spark-master-service
    spec:
      containers:
        - name: spark-master-service
          image: elkinmle19/spark-hadoop:3.2.0
          command: ["/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m