apiVersion: v1
kind: Service
metadata:
  name: k8s-flask-nginx
spec:
  type: LoadBalancer
  selector:
    app: k8s-flask-nginx
  ports:
  - port: 9696
    targetPort: 9696
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-flask-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-flask-nginx
  template:
    metadata:
      labels:
        app: k8s-flask-nginx
    spec:
      containers:
      - name: k8s-flask-nginx
        image: elkinmle19/dev-images:k8s-simple-flask-nginx
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000